<?php

use Illuminate\Database\Seeder;

class PegawaiSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::insert("INSERT INTO `pgw_pegawai` (`id_skpd`, `id_eselon`, `id_pangkat`, `id_pangkat_golongan`, `id_jabatan`, `id_level`, `nip`, `nama`, `nama_asli`, `jenjab`, `is_deleted`) VALUES (26, 2, 3, 3, 29, 4, '197007151990091002', 'Drs. Pupung Wahyu Purnama, M.Si', 'Pupung Wahyu Purnama', '', 0);");
		 DB::insert("INSERT INTO `pgw_pegawai` (`id_skpd`, `id_eselon`, `id_pangkat`, `id_pangkat_golongan`, `id_jabatan`, `id_level`, `nip`, `nama`, `nama_asli`, `jenjab`, `is_deleted`) VALUES (26, 3, 3, 3, 36, 3, '196304081983031007', 'Arie Sarsono Budiraharjo, S.E.,M.Pd.', 'Arie Sarsono Budiraharjo', '', 0);");
		 DB::insert("INSERT INTO `pgw_pegawai` (`id_skpd`, `id_eselon`, `id_pangkat`, `id_pangkat_golongan`, `id_jabatan`, `id_level`, `nip`, `nama`, `nama_asli`, `jenjab`, `is_deleted`) VALUES (26, 3, 3, 3, 49, 3, '196204041992112001', 'Dra. Hj. Ira Sulistyanti, M.M.', 'Ira Sulistyanti', '', 0);");
		 DB::insert("INSERT INTO `pgw_pegawai` (`id_skpd`, `id_eselon`, `id_pangkat`, `id_pangkat_golongan`, `id_jabatan`, `id_level`, `nip`, `nama`, `nama_asli`, `jenjab`, `is_deleted`) VALUES (26, 3, 3, 3, 56, 3, '197209181999011001', 'Novy Hasbhy Munnawar, S.H., M.Si.', 'Novy Hasbhy Munnawar', '', 0);");
		 DB::insert("INSERT INTO `pgw_pegawai` (`id_skpd`, `id_eselon`, `id_pangkat`, `id_pangkat_golongan`, `id_jabatan`, `id_level`, `nip`, `nama`, `nama_asli`, `jenjab`, `is_deleted`) VALUES (26, 3, 4, 4, 74, 3, '196606261993031007', 'Drs. Dwi Raharjo', 'Dwi Raharjo', '', 0);");
		 DB::insert("INSERT INTO `pgw_pegawai` (`id_skpd`, `id_eselon`, `id_pangkat`, `id_pangkat_golongan`, `id_jabatan`, `id_level`, `nip`, `nama`, `nama_asli`, `jenjab`, `is_deleted`) VALUES (26, 5, 5, 5, 364, 2, '197406142006042010', 'Indriyani Yuni Nugraha, S.H.', 'Indriyani Yuni Nugraha', '', 0);");
		 DB::insert("INSERT INTO `pgw_pegawai` (`id_skpd`, `id_eselon`, `id_pangkat`, `id_pangkat_golongan`, `id_jabatan`, `id_level`, `nip`, `nama`, `nama_asli`, `jenjab`, `is_deleted`) VALUES (26, 5, 6, 6, 606, 2, '198310012010011013', 'Riki Riswan Deris, S.T., MM', 'Riki Riswan Deris', '', 0);");
		 DB::insert("INSERT INTO `pgw_pegawai` (`id_skpd`, `id_eselon`, `id_pangkat`, `id_pangkat_golongan`, `id_jabatan`, `id_level`, `nip`, `nama`, `nama_asli`, `jenjab`, `is_deleted`) VALUES (26, 7, 2, 2, 977, 6, '196507271991032008', 'Dra. Siti Nuryani', 'Siti Nuryani', '', 0);");
		 DB::insert("INSERT INTO `pgw_pegawai` (`id_skpd`, `id_eselon`, `id_pangkat`, `id_pangkat_golongan`, `id_jabatan`, `id_level`, `nip`, `nama`, `nama_asli`, `jenjab`, `is_deleted`) VALUES (26, 7, 3, 3, 977, 6, '196607051997031005', 'Aa Pardikusumah, S.E.', 'Aa Pardikusumah', '', 0);");
		 DB::insert("INSERT INTO `pgw_pegawai` (`id_skpd`, `id_eselon`, `id_pangkat`, `id_pangkat_golongan`, `id_jabatan`, `id_level`, `nip`, `nama`, `nama_asli`, `jenjab`, `is_deleted`) VALUES (26, 7, 3, 3, 977, 6, '197006161996122001', 'Ayi Suryaning Ati, S.E.', 'Ayi Suryaning Ati', '', 0);");
		 DB::insert("INSERT INTO `pgw_pegawai` (`id_skpd`, `id_eselon`, `id_pangkat`, `id_pangkat_golongan`, `id_jabatan`, `id_level`, `nip`, `nama`, `nama_asli`, `jenjab`, `is_deleted`) VALUES (26, 7, 3, 3, 977, 6, '196004181987012001', 'Titik Supiati, SE', 'Titik Supiati', '', 0);");
		 DB::insert("INSERT INTO `pgw_pegawai` (`id_skpd`, `id_eselon`, `id_pangkat`, `id_pangkat_golongan`, `id_jabatan`, `id_level`, `nip`, `nama`, `nama_asli`, `jenjab`, `is_deleted`) VALUES (26, 7, 4, 4, 977, 6, '197106071999032005', 'Eny Sadyantri, S.H , M.Si', 'Eny Sadyantri', '', 0);");
		 DB::insert("INSERT INTO `pgw_pegawai` (`id_skpd`, `id_eselon`, `id_pangkat`, `id_pangkat_golongan`, `id_jabatan`, `id_level`, `nip`, `nama`, `nama_asli`, `jenjab`, `is_deleted`) VALUES (26, 7, 4, 4, 977, 6, '197101221998032004', 'Firdiani, S.H., M.Si', 'Firdiani', '', 0);");
		 DB::insert("INSERT INTO `pgw_pegawai` (`id_skpd`, `id_eselon`, `id_pangkat`, `id_pangkat_golongan`, `id_jabatan`, `id_level`, `nip`, `nama`, `nama_asli`, `jenjab`, `is_deleted`) VALUES (26, 7, 4, 4, 977, 6, '197604201998032003', 'Lilis Suliyanti, S.E ,M.Si.', 'Lilis Suliyanti', '', 0);");
		 DB::insert("INSERT INTO `pgw_pegawai` (`id_skpd`, `id_eselon`, `id_pangkat`, `id_pangkat_golongan`, `id_jabatan`, `id_level`, `nip`, `nama`, `nama_asli`, `jenjab`, `is_deleted`) VALUES (26, 7, 4, 4, 1001, 6, '196509101985031009', 'Raden Herry Suherman Suryana, S.H., M.Si', 'Raden Herry Suherman Suryana', '', 0);");
		 DB::insert("INSERT INTO `pgw_pegawai` (`id_skpd`, `id_eselon`, `id_pangkat`, `id_pangkat_golongan`, `id_jabatan`, `id_level`, `nip`, `nama`, `nama_asli`, `jenjab`, `is_deleted`) VALUES (26, 7, 5, 5, 1009, 6, '196905282005011003', 'Ade Hendar Purnawan, S.T , M.P.', 'Ade Hendar Purnawan', '', 0);");
		 DB::insert("INSERT INTO `pgw_pegawai` (`id_skpd`, `id_eselon`, `id_pangkat`, `id_pangkat_golongan`, `id_jabatan`, `id_level`, `nip`, `nama`, `nama_asli`, `jenjab`, `is_deleted`) VALUES (26, 7, 5, 5, 978, 6, '197304242005011004', 'Andreis Prilesmana Sukanda, S.E.', 'Andreis Prilesmana Sukanda', '', 0);");
		 DB::insert("INSERT INTO `pgw_pegawai` (`id_skpd`, `id_eselon`, `id_pangkat`, `id_pangkat_golongan`, `id_jabatan`, `id_level`, `nip`, `nama`, `nama_asli`, `jenjab`, `is_deleted`) VALUES (26, 7, 5, 5, 1009, 6, '197607042006041011', 'Budi Yulistiawan, S.T.', 'Budi Yulistiawan', '', 0);");
		 DB::insert("INSERT INTO `pgw_pegawai` (`id_skpd`, `id_eselon`, `id_pangkat`, `id_pangkat_golongan`, `id_jabatan`, `id_level`, `nip`, `nama`, `nama_asli`, `jenjab`, `is_deleted`) VALUES (26, 7, 5, 5, 1020, 6, '198507042003122001', 'Choeriah Fitriani, S.STP.', 'Choeriah Fitriani', '', 0);");
		 DB::insert("INSERT INTO `pgw_pegawai` (`id_skpd`, `id_eselon`, `id_pangkat`, `id_pangkat_golongan`, `id_jabatan`, `id_level`, `nip`, `nama`, `nama_asli`, `jenjab`, `is_deleted`) VALUES (26, 7, 5, 5, 1009, 6, '196808091997032001', 'E. Sulistiawarni, SE, Ak', 'E. Sulistiawarni', '', 0);");
		 DB::insert("INSERT INTO `pgw_pegawai` (`id_skpd`, `id_eselon`, `id_pangkat`, `id_pangkat_golongan`, `id_jabatan`, `id_level`, `nip`, `nama`, `nama_asli`, `jenjab`, `is_deleted`) VALUES (26, 7, 5, 5, 1009, 6, '197304222005011010', 'Edi Kurniadi Kosasih, ST.', 'Edi Kurniadi Kosasih', '', 0);");
		 DB::insert("INSERT INTO `pgw_pegawai` (`id_skpd`, `id_eselon`, `id_pangkat`, `id_pangkat_golongan`, `id_jabatan`, `id_level`, `nip`, `nama`, `nama_asli`, `jenjab`, `is_deleted`) VALUES (26, 7, 5, 5, 1020, 6, '198402102003122001', 'Ferani Miranty, S.STP, MM', 'Ferani Miranty', '', 0);");
		 DB::insert("INSERT INTO `pgw_pegawai` (`id_skpd`, `id_eselon`, `id_pangkat`, `id_pangkat_golongan`, `id_jabatan`, `id_level`, `nip`, `nama`, `nama_asli`, `jenjab`, `is_deleted`) VALUES (26, 7, 5, 5, 1031, 6, '197406121997031005', 'Ficki Abdullah Rizky, B.E., M.Si.', 'Ficki Abdullah Rizky', '', 0);");
		 DB::insert("INSERT INTO `pgw_pegawai` (`id_skpd`, `id_eselon`, `id_pangkat`, `id_pangkat_golongan`, `id_jabatan`, `id_level`, `nip`, `nama`, `nama_asli`, `jenjab`, `is_deleted`) VALUES (26, 7, 5, 5, 1035, 6, '197102071998031010', 'Hilman Haerudin, S.T., M T.', 'Hilman Haerudin', '', 0);");
		 DB::insert("INSERT INTO `pgw_pegawai` (`id_skpd`, `id_eselon`, `id_pangkat`, `id_pangkat_golongan`, `id_jabatan`, `id_level`, `nip`, `nama`, `nama_asli`, `jenjab`, `is_deleted`) VALUES (26, 7, 5, 5, 1009, 6, '198210202006042006', 'Mahdalena, S.E , M.Si', 'Mahdalena', '', 0);");
		 DB::insert("INSERT INTO `pgw_pegawai` (`id_skpd`, `id_eselon`, `id_pangkat`, `id_pangkat_golongan`, `id_jabatan`, `id_level`, `nip`, `nama`, `nama_asli`, `jenjab`, `is_deleted`) VALUES (26, 7, 5, 5, 1009, 6, '197503271994032002', 'Siti Nurlaelah, SAP', 'Siti Nurlaelah', '', 0);");
		 DB::insert("INSERT INTO `pgw_pegawai` (`id_skpd`, `id_eselon`, `id_pangkat`, `id_pangkat_golongan`, `id_jabatan`, `id_level`, `nip`, `nama`, `nama_asli`, `jenjab`, `is_deleted`) VALUES (26, 7, 5, 5, 1035, 6, '196611121994031006', 'Tonina Gunawan, S.T.', 'Tonina Gunawan', '', 0);");
		 DB::insert("INSERT INTO `pgw_pegawai` (`id_skpd`, `id_eselon`, `id_pangkat`, `id_pangkat_golongan`, `id_jabatan`, `id_level`, `nip`, `nama`, `nama_asli`, `jenjab`, `is_deleted`) VALUES (26, 7, 5, 5, 1009, 6, '197503162010011009', 'Widiatmoko, S.T, M.M', 'Widiatmoko', '', 0);");
		 DB::insert("INSERT INTO `pgw_pegawai` (`id_skpd`, `id_eselon`, `id_pangkat`, `id_pangkat_golongan`, `id_jabatan`, `id_level`, `nip`, `nama`, `nama_asli`, `jenjab`, `is_deleted`) VALUES (26, 7, 6, 6, 1009, 6, '197509052006042016', 'Dewi Ekaningsih, S.E.', 'Dewi Ekaningsih', '', 0);");
		 DB::insert("INSERT INTO `pgw_pegawai` (`id_skpd`, `id_eselon`, `id_pangkat`, `id_pangkat_golongan`, `id_jabatan`, `id_level`, `nip`, `nama`, `nama_asli`, `jenjab`, `is_deleted`) VALUES (26, 7, 6, 6, 1009, 6, '196907061997032003', 'Dewi Lesmana, SE', 'Dewi Lesmana', '', 0);");
		 DB::insert("INSERT INTO `pgw_pegawai` (`id_skpd`, `id_eselon`, `id_pangkat`, `id_pangkat_golongan`, `id_jabatan`, `id_level`, `nip`, `nama`, `nama_asli`, `jenjab`, `is_deleted`) VALUES (26, 7, 6, 6, 1009, 6, '198308072010012017', 'Ferawaty Sitorus, S.E.', 'Ferawaty Sitorus', '', 0);");
		 DB::insert("INSERT INTO `pgw_pegawai` (`id_skpd`, `id_eselon`, `id_pangkat`, `id_pangkat_golongan`, `id_jabatan`, `id_level`, `nip`, `nama`, `nama_asli`, `jenjab`, `is_deleted`) VALUES (26, 7, 6, 6, 1009, 6, '197505262009021001', 'Makmur Ridho, S.T.', 'Makmur Ridho', '', 0);");
		 DB::insert("INSERT INTO `pgw_pegawai` (`id_skpd`, `id_eselon`, `id_pangkat`, `id_pangkat_golongan`, `id_jabatan`, `id_level`, `nip`, `nama`, `nama_asli`, `jenjab`, `is_deleted`) VALUES (26, 7, 6, 6, 1009, 6, '198109182010011012', 'Rizki Satrianegara , S.E.', 'Rizki Satrianegara ', '', 0);");
		 DB::insert("INSERT INTO `pgw_pegawai` (`id_skpd`, `id_eselon`, `id_pangkat`, `id_pangkat_golongan`, `id_jabatan`, `id_level`, `nip`, `nama`, `nama_asli`, `jenjab`, `is_deleted`) VALUES (26, 7, 6, 6, 1009, 6, '196801231993031003', 'Sarmudi, S.E', 'Sarmudi', '', 0);");
		 DB::insert("INSERT INTO `pgw_pegawai` (`id_skpd`, `id_eselon`, `id_pangkat`, `id_pangkat_golongan`, `id_jabatan`, `id_level`, `nip`, `nama`, `nama_asli`, `jenjab`, `is_deleted`) VALUES (26, 7, 6, 6, 1009, 6, '198509012009022002', 'Septi Ekariani, S.E.', 'Septi Ekariani', '', 0);");
		 DB::insert("INSERT INTO `pgw_pegawai` (`id_skpd`, `id_eselon`, `id_pangkat`, `id_pangkat_golongan`, `id_jabatan`, `id_level`, `nip`, `nama`, `nama_asli`, `jenjab`, `is_deleted`) VALUES (26, 7, 6, 6, 1009, 6, '197309192003122002', 'Sisca Irma Trisiana, S.E.', 'Sisca Irma Trisiana', '', 0);");
		 DB::insert("INSERT INTO `pgw_pegawai` (`id_skpd`, `id_eselon`, `id_pangkat`, `id_pangkat_golongan`, `id_jabatan`, `id_level`, `nip`, `nama`, `nama_asli`, `jenjab`, `is_deleted`) VALUES (26, 7, 6, 6, 1009, 6, '198007162010011012', 'Tri Suharto, S.E.', 'Tri Suharto', '', 0);");
		 DB::insert("INSERT INTO `pgw_pegawai` (`id_skpd`, `id_eselon`, `id_pangkat`, `id_pangkat_golongan`, `id_jabatan`, `id_level`, `nip`, `nama`, `nama_asli`, `jenjab`, `is_deleted`) VALUES (26, 7, 6, 6, 1143, 6, '197008281993032008', 'Yusfa Reno', 'Yusfa Reno', '', 0);");
		 DB::insert("INSERT INTO `pgw_pegawai` (`id_skpd`, `id_eselon`, `id_pangkat`, `id_pangkat_golongan`, `id_jabatan`, `id_level`, `nip`, `nama`, `nama_asli`, `jenjab`, `is_deleted`) VALUES (26, 7, 7, 7, 1020, 6, '198804172015022001', 'Apriessa Seventienna, S.E.', 'Apriessa Seventienna', '', 0);");
		 DB::insert("INSERT INTO `pgw_pegawai` (`id_skpd`, `id_eselon`, `id_pangkat`, `id_pangkat_golongan`, `id_jabatan`, `id_level`, `nip`, `nama`, `nama_asli`, `jenjab`, `is_deleted`) VALUES (26, 7, 7, 7, 1020, 6, '197803102010012011', 'Areh Setiawati, SE', 'Areh Setiawati', '', 0);");
		 DB::insert("INSERT INTO `pgw_pegawai` (`id_skpd`, `id_eselon`, `id_pangkat`, `id_pangkat_golongan`, `id_jabatan`, `id_level`, `nip`, `nama`, `nama_asli`, `jenjab`, `is_deleted`) VALUES (26, 7, 7, 7, 1020, 6, '198407302015021001', 'Bernadus Danarjati, ST', 'Bernadus Danarjati', '', 0);");
		 DB::insert("INSERT INTO `pgw_pegawai` (`id_skpd`, `id_eselon`, `id_pangkat`, `id_pangkat_golongan`, `id_jabatan`, `id_level`, `nip`, `nama`, `nama_asli`, `jenjab`, `is_deleted`) VALUES (26, 7, 7, 7, 1220, 6, '198009062008011007', 'Mamat Rohimat, S.Sos', 'Mamat Rohimat', '', 0);");
		 DB::insert("INSERT INTO `pgw_pegawai` (`id_skpd`, `id_eselon`, `id_pangkat`, `id_pangkat_golongan`, `id_jabatan`, `id_level`, `nip`, `nama`, `nama_asli`, `jenjab`, `is_deleted`) VALUES (26, 7, 7, 7, 1042, 6, '196208271998031002', 'Purnomo', 'Purnomo', '', 0);");
		 DB::insert("INSERT INTO `pgw_pegawai` (`id_skpd`, `id_eselon`, `id_pangkat`, `id_pangkat_golongan`, `id_jabatan`, `id_level`, `nip`, `nama`, `nama_asli`, `jenjab`, `is_deleted`) VALUES (26, 7, 7, 7, 1042, 6, '196803241996011001', 'Rasdi Cahyadi', 'Rasdi Cahyadi', '', 0);");
		 DB::insert("INSERT INTO `pgw_pegawai` (`id_skpd`, `id_eselon`, `id_pangkat`, `id_pangkat_golongan`, `id_jabatan`, `id_level`, `nip`, `nama`, `nama_asli`, `jenjab`, `is_deleted`) VALUES (26, 7, 7, 7, 1020, 6, '198304042015022001', 'Ratih Werdiningsih Suherman, S.Pi., MM.', 'Ratih Werdiningsih Suherman', '', 0);");
		 DB::insert("INSERT INTO `pgw_pegawai` (`id_skpd`, `id_eselon`, `id_pangkat`, `id_pangkat_golongan`, `id_jabatan`, `id_level`, `nip`, `nama`, `nama_asli`, `jenjab`, `is_deleted`) VALUES (26, 7, 7, 7, 1020, 6, '198603182015021001', 'Supian Ardyanumbara, SE', 'Supian Ardyanumbara', '', 0);");
		 DB::insert("INSERT INTO `pgw_pegawai` (`id_skpd`, `id_eselon`, `id_pangkat`, `id_pangkat_golongan`, `id_jabatan`, `id_level`, `nip`, `nama`, `nama_asli`, `jenjab`, `is_deleted`) VALUES (26, 7, 8, 8, 1020, 6, '198309292010011001', 'Muhamad Dahlan, SE', 'Muhamad Dahlan', '', 0);");
		 DB::insert("INSERT INTO `pgw_pegawai` (`id_skpd`, `id_eselon`, `id_pangkat`, `id_pangkat_golongan`, `id_jabatan`, `id_level`, `nip`, `nama`, `nama_asli`, `jenjab`, `is_deleted`) VALUES (26, 7, 8, 8, 1333, 6, '197802232014091001', 'Rudy Suryadi, SE', 'Rudy Suryadi', '', 0);");
		 DB::insert("INSERT INTO `pgw_pegawai` (`id_skpd`, `id_eselon`, `id_pangkat`, `id_pangkat_golongan`, `id_jabatan`, `id_level`, `nip`, `nama`, `nama_asli`, `jenjab`, `is_deleted`) VALUES (26, 7, 8, 8, 1333, 6, '198007062008012007', 'Sutiyawati, S.E.', 'Sutiyawati', '', 0);");
		 DB::insert("INSERT INTO `pgw_pegawai` (`id_skpd`, `id_eselon`, `id_pangkat`, `id_pangkat_golongan`, `id_jabatan`, `id_level`, `nip`, `nama`, `nama_asli`, `jenjab`, `is_deleted`) VALUES (26, 7, 8, 8, 1095, 6, '198502152010012014', 'Vina Mardiana Saragi, A.Md', 'Vina Mardiana Saragi', '', 0);");
		 DB::insert("INSERT INTO `pgw_pegawai` (`id_skpd`, `id_eselon`, `id_pangkat`, `id_pangkat_golongan`, `id_jabatan`, `id_level`, `nip`, `nama`, `nama_asli`, `jenjab`, `is_deleted`) VALUES (26, 7, 8, 8, 1333, 6, '197301152008011005', 'Wardi Suwardi, SE', 'Wardi Suwardi', '', 0);");
		 DB::insert("INSERT INTO `pgw_pegawai` (`id_skpd`, `id_eselon`, `id_pangkat`, `id_pangkat_golongan`, `id_jabatan`, `id_level`, `nip`, `nama`, `nama_asli`, `jenjab`, `is_deleted`) VALUES (26, 7, 10, 10, 1136, 6, '196504052007011018', 'Alpian', 'Alpian', '', 0);");
    }
}
